export default {
  WOLF_MOVE_MIN_MILISEC: 2000,
  FREE_ID: 0,
  RABBIT_ID: 1,
  HOUSE_ID: 2,
  WOLF_ID: 3,
  FENCE_ID: 4,
  X: 0,
  Y: 1,
  UNIT_SIZE: 76,
  gameBoardNum: 0,
  GAME_STATES: {},
  isGameRunning: true,
  IMAGES: {
    0: "Images/1x1.png",
    1: "Images/rabbit.png",
    2: "Images/house.png",
    3: "Images/wolf.png",
    4: "Images/fence.png",
  },
}
